### ISSUE TITLE
Issue with "user_id" parameter

### ISSUE THREAD

**Issue by jacovm** [hrvojevu/xblock-lti-consumer#1]
The xblock seems to put a course-specific ID into the "user_id" parameter, and create some other parameter with a nonstandard name to contain the data that should be in the standard field.
According to the LTI standard, the parameter "user_id" is supposed to contain a persistent, platform-wide ID. 

Consequently, LTI tools utilizing "user_id" may not function as expected.

**Comment by hrvojevu** [comment]
Yes indeed XBlock sends user's course-specific ID in "user_id" parameter. This is just the way edX and this LTI Consumer XBlock works. Since I couldn't change this parameter without potentially messing whole XBlock up, I added another LTI parameter that is sent and that contains unique user ID. That parameter is "custom_user_id".

**Comment by jacovm** [comment]
Hello hrvojevu, thank you for your reply.
Would it be possible to allow "custom_user_id" to be configurable? E.g., allow a configuration to specify what the unique user ID parameter is named?
That way this parameter can be setup to use whatever name an LTI tool is expecting, rather than having to customize any LTI tool itself.
Blackboard LMS used a similar approach to address such an issue.
Thanks

**Comment by natea** [comment]
@hrvojevu here's a brief description of the technical issue with the XBlock that's blocking us from moving forward with the LTI integration.

Since edX deviated from the LTI standard by sending over a "non-standard" user ID, the LTI consumer XBlock is sending over the "standard" user ID as a custom parameter. 

What we'd like to request is to allow the name of the custom parameter to be configured. When setting up an LTI tool this will allow the administrator to name the custom parameter according to what each LTI tool is expecting - as each LTI tool (including ours) may have a different naming convention for custom parameters. 

This is the way others including Blackboard Learn LMS have approached a similar issues.
